In [13]:
from scipy.integrate import solve_ivp
from scipy import linalg
import numpy as np
import matplotlib.pyplot as plt

In [14]:
dim = 5

In [73]:
for _ in range(1000):
    A = np.random.normal(0, 2, size=(dim, dim))

    norms_a = []
    norms_b = []

    for _ in range(10_000):
        X = np.random.uniform(0, 1, size=(dim, dim))
        I = np.identity(dim)

        norms_a.append(np.linalg.norm(A @ I) / np.linalg.norm(I))
        norms_b.append(np.linalg.norm(A @ X) / np.linalg.norm(X))

    assert np.mean(norms_a) > np.mean(norms_b)

    print("OK")

AssertionError: 

In [34]:
dim**(1/3)

1.7099759466766968

In [59]:
np.mean(norms_a), np.mean(norms_b)

(np.float64(10.19341054630141), np.float64(10.288747119968889))

In [58]:
for _ in range(500_000):
    X = np.random.uniform(0, 1, size=(dim, dim))
    # X = np.ones((dim, dim))
    I = np.identity(dim)

    norms_a.append(np.linalg.norm(A @ I) / np.linalg.norm(I))
    norms_b.append(np.linalg.norm(A @ X) / np.linalg.norm(X))

assert np.mean(norms_a) > np.mean(norms_b)


AssertionError: 

In [68]:
A.sum(axis=1)

array([ 0.15149507,  4.59213304, -3.21174   , -3.22039461, 15.34933201])

In [67]:
A.diagonal()

array([ 2.8833887 , 10.98284305,  8.81866342,  2.8163751 , 21.19130221])

In [64]:
A

array([[ 1.74656297e+01, -2.22092203e-01, -1.58070559e+00,
        -5.57665713e-01, -9.92548190e-01],
       [-4.40927966e+00,  2.43888277e+00, -1.17610741e+00,
        -9.97538271e-03, -1.63238256e+00],
       [-1.28411817e+00, -1.37841479e+00,  7.55274575e+00,
        -7.49772826e-01, -2.87683330e-02],
       [-2.93645227e+00, -6.76978170e+00, -2.35202577e-01,
         7.07552077e-01, -3.66857988e+00],
       [-3.13097019e+00, -2.20861211e+00, -5.39439678e+00,
        -2.36903479e+00,  1.47716853e+00]])